name: Silpion Craft-Night example

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 8, 10, 12 ]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test application
        env:
          SECRET: ${{ secrets.test }}
        run: npm run test
