name: Silpion Craft-Night example

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test application
        run: npm run test
